name: risknotifier
description: "A new Flutter project."


publish_to: "none" 













version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"







dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  geolocator: ^8.0.0
  geocoding: ^2.0.0
  circle_nav_bar: ^2.1.0+1
  url_launcher: ^6.3.0
  bottom_bar: ^2.0.3
  
  
  cupertino_icons: ^1.0.6
  curved_navigation_bar: ^1.0.6
  http: ^1.2.2
  smooth_page_indicator: ^1.2.0+3
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  icons_launcher: ^2.1.7
  dio: ^5.6.0
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0





flutter:
  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/

  

 
icons_launcher:
  image_path: "assets/images/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true 

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
